theme: jekyll-theme-minimal
title: Virtuální prohlídka školy
description: Mapujeme chodby Mensa gymnázia!
logo: http://honbraofficial.github.io/index_image.png
show_downloads: false
show_github: false
